[package]
name = "wgpu_studies"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.14"
winit = "0.27"
env_logger = "0.9"
log = "0.4"
